"""C2PA trust anchor service — lightweight key registration in R2.

Maintains a JSON registry of all active signing keys so that consumers can:

  1. Look up the trust anchor for a given key_id or DID
  2. Verify the key was registered at a known time (first_seen)
  3. Check whether a key is still active or has been rotated

The trust anchor is stored as a JSON document in R2 at a well-known path:
  `_c2pa/trust_anchor/registry.json`

This is NOT a global C2PA trust anchor (which requires membership in the
C2PA steering committee). It is a self-hosted trust anchor that:

  - Proves this AI Director instance generated the clip
  - Enables any consumer to verify the key material
  - Provides a chain of custody record (first_seen, last_seen, rotation)

To upgrade to a full C2PA-compliant trust anchor, register with:
  https://contentcredentials.org/verify

Usage:
    ta = get_trust_anchor()
    ta.register_key(key_id="default-v1", did="did:key:z...", public_key_b64="...")
    status = ta.verify_key(key_id="default-v1")
"""

from __future__ import annotations

import json
import logging
import time
from datetime import datetime, timezone
from typing import Any

from api.config import get_settings

log = logging.getLogger(__name__)

# R2 key for the trust anchor registry
_TRUST_ANCHOR_KEY = "_c2pa/trust_anchor/registry.json"
# In-memory cache TTL
_REGISTRY_CACHE_TTL_S = 300

# Trust levels for key registration
_TRUST_LEVEL_SELF = "self"  # Generated by this AI Director instance
_TRUST_LEVEL_VERIFIED = "verified"  # Verified by out-of-band process


class TrustAnchorService:
    """Self-hosted C2PA trust anchor — key registry in R2.

    Thread-safe (no mutable shared state after __init__). Singleton per
    process — instantiate via `get_trust_anchor()`.
    """

    def __init__(self, settings=None) -> None:
        self._settings = settings or get_settings()
        self._registry: dict[str, Any] | None = None
        self._registry_ts: float = 0.0

    # ── Public API ─────────────────────────────────────────────────────────

    def register_key(
        self,
        *,
        key_id: str,
        did: str,
        public_key_b64: str,
        trust_level: str = _TRUST_LEVEL_SELF,
    ) -> dict[str, Any]:
        """Register or update a signing key in the trust anchor registry.

        If the key already exists (same key_id), `last_seen` is updated but
        `first_seen` is preserved. Returns the registry entry.
        """
        registry = self._load_registry()

        now_iso = datetime.now(timezone.utc).isoformat()
        existing = registry.get(key_id)

        if existing:
            existing["last_seen"] = now_iso
            existing["public_key_b64"] = public_key_b64
            existing["did"] = did
            if existing.get("trust_level") == _TRUST_LEVEL_SELF:
                existing["trust_level"] = trust_level
            entry = existing
        else:
            entry = {
                "key_id": key_id,
                "did": did,
                "public_key_b64": public_key_b64,
                "trust_level": trust_level,
                "first_seen": now_iso,
                "last_seen": now_iso,
                "status": "active",
            }
            registry[key_id] = entry

        self._save_registry(registry)
        log.info("trust_anchor: registered key_id=%s did=%s", key_id, did)
        return entry

    def verify_key(self, key_id: str) -> dict[str, Any] | None:
        """Look up a key in the trust anchor registry.

        Returns the registry entry dict, or None if the key is unknown.
        Consumers should check:
          - `status == "active"`
          - `trust_level` is at least "self"
          - `first_seen` is before the clip's signed_at timestamp
        """
        registry = self._load_registry()
        entry = registry.get(key_id)
        if entry is None:
            log.debug("trust_anchor: key_id=%s not found in registry", key_id)
        return entry

    def rotate_key(
        self,
        old_key_id: str,
        new_key_id: str,
        new_did: str,
        new_public_key_b64: str,
    ) -> dict[str, Any]:
        """Mark an old key as rotated and register a new one.

        Returns the new key's registry entry.
        """
        registry = self._load_registry()

        # Mark old key as rotated
        if old_key_id in registry:
            registry[old_key_id]["status"] = "rotated"
            registry[old_key_id]["rotated_at"] = datetime.now(timezone.utc).isoformat()
            registry[old_key_id]["replaced_by"] = new_key_id

        # Register new key (inherits trust level from old key)
        old_trust = registry.get(old_key_id, {}).get("trust_level", _TRUST_LEVEL_SELF)
        entry = self.register_key(
            key_id=new_key_id,
            did=new_did,
            public_key_b64=new_public_key_b64,
            trust_level=old_trust,
        )

        self._save_registry(registry)
        log.info("trust_anchor: rotated %s → %s", old_key_id, new_key_id)
        return entry

    def get_registry_url(self) -> str:
        """Return a presigned URL to the registry JSON."""
        from api.services import r2

        return r2.signed_get_url(_TRUST_ANCHOR_KEY, expires_s=86400)

    def get_registry_json(self) -> dict[str, Any]:
        """Return the full registry as a dict (for API responses)."""
        registry = self._load_registry()
        return {
            "anchor": {
                "type": "self-hosted",
                "instance": getattr(self._settings, "app_name", "ai-director"),
                "registry_updated_at": datetime.now(timezone.utc).isoformat(),
            },
            "keys": registry,
        }

    # ── Internals ──────────────────────────────────────────────────────────

    def _load_registry(self) -> dict[str, Any]:
        """Load registry from R2 (with in-memory cache)."""
        now = time.monotonic()
        if self._registry is not None and (now - self._registry_ts) < _REGISTRY_CACHE_TTL_S:
            return self._registry

        try:
            body = self._get_from_r2(_TRUST_ANCHOR_KEY)
            if body:
                self._registry = json.loads(body)
            else:
                self._registry = {}
        except Exception:
            log.debug("trust_anchor: no existing registry found, starting fresh")
            self._registry = {}

        self._registry_ts = now
        return self._registry

    def _save_registry(self, registry: dict[str, Any]) -> None:
        """Write registry to R2."""
        body = json.dumps(registry, indent=2).encode()
        self._put_to_r2(_TRUST_ANCHOR_KEY, body)
        self._registry = registry
        self._registry_ts = time.monotonic()

    @staticmethod
    def _get_from_r2(key: str) -> bytes | None:
        """Fetch an object from R2 by key."""
        from api.services import r2

        try:
            return r2.get_object(key)
        except Exception:
            return None

    @staticmethod
    def _put_to_r2(key: str, body: bytes) -> None:
        """Write bytes to R2."""
        import boto3

        _s = get_settings()
        client = boto3.client(
            "s3",
            endpoint_url=f"https://{_s.r2_account_id}.r2.cloudflarestorage.com",
            aws_access_key_id=_s.r2_access_key_id,
            aws_secret_access_key=_s.r2_secret_access_key,
        )
        client.put_object(
            Bucket=_s.r2_bucket,
            Key=key,
            Body=body,
            ContentType="application/json",
        )


# ── Module-level singleton ─────────────────────────────────────────────────


_trust_anchor: TrustAnchorService | None = None


def get_trust_anchor(settings=None) -> TrustAnchorService:
    """Return the process-wide TrustAnchorService singleton."""
    global _trust_anchor
    if _trust_anchor is None:
        _trust_anchor = TrustAnchorService(settings=settings)
    return _trust_anchor
